name: E2E Tests

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  # Allow manual trigger
  workflow_dispatch:

env:
  NEXT_PUBLIC_APPWRITE_PROJECT_ID: test-project-id
  NEXT_PUBLIC_APPWRITE_ENDPOINT: http://localhost/v1
  NEXT_PUBLIC_APPWRITE_DATABASE_ID: test-database-id
  APPWRITE_API_KEY: test-api-key

jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup Bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest

      - name: Install dependencies
        run: |
          bun install
          bunx playwright install --with-deps

      - name: Create auth directory
        run: mkdir -p playwright/.auth

      - name: Build Next.js app
        run: bun run build

      - name: Run Playwright tests
        run: bun run test:e2e

      - name: Upload test results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: playwright-report
          path: |
            playwright-report/
            test-results/
          retention-days: 30

      - name: Upload test results (HTML)
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: playwright-report-html
          path: playwright-report
          retention-days: 30

      - name: Upload test results (JUnit)
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: playwright-junit
          path: reports/playwright-junit.xml
          retention-days: 30
